server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka

spring:
  application:
    name: authentication-server

  datasource:
    url: jdbc:${DATASOURCE_DB:mysql}://${DATASOURCE_HOST:49.233.168.132}:${DATASOURCE_PORT:3306}/sc_admin?characterEncoding=utf8
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:Shi18740961619?}
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

