spring:
  application:
    name: registry

server:
  port: 8888
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://registry:8888/eureka/


