
server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Siwanper/SpringCloud-Leaning/
          search-paths: 5-spring-cloud-git/config-repo
          username: Siwanper
          password: Shi18740961619
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka

