server:
  port: 9001
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Siwanper/SpringCloud-Leaning/
          search-paths: spring-cloud-module/spring-cloud-module/config-repo
          username: Siwanper
          password: Shi18740961619

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
management:
  security:
    enabled: false

