
server:
  port: 9000

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  instance:
    hostname: gateway
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug