
server:
  port: 8010

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka

spring:
  application:
    name: organization

  datasource:
    url: jdbc:${DATASOURCE_DB:mysql}://${DATASOURCE_HOST:47.105.184.71}:${DATASOURCE_PORT:3306}/sc_admin?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:Shi18740961619?}
    driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PROT:6379}
    lettuce:
      pool:
        max-active: 300
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-file-size: "2MB"
      max-request-size: "2MB"
  jackson:
    time-zone: GMT+8


logging:
  level:
    com.swp.cloud: debug
    java.sql.PreparedStatement: debug
  path: logs/
  file:
    max-size: 1GB

management:
  endpoints:
    web:
      exposure:
        include: "*"

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: "Y" # 逻辑已删除值(默认为 Y)
      logic-not-delete-value: "N" # 逻辑未删除值(默认为 N)