server:
  port: 9999
spring:
  application:
    name: spring-boot-admin-server

  security:
    user:
      name: siwanper
      password: 123456
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
eureka:
  instance:
    metadata-map:
      user.name: siwanper
      user.password: 123456
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}

  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://siwanper:101088@127.0.0.1:8888/eureka/
