version: '3'
services:

  gateway:
    image: spring-boot-cloud/gateway
    hostname: gateway
    restart: on-failure
    ports:
      - "9000:9000"
    external_links:
      - registry
      - rabbitmq
      - config

  oauth:
    image: spring-boot-cloud/oauth
    hostname: oauth
    restart: on-failure
    ports:
      - "5000:5000"
    external_links:
      - registry
      - rabbitmq
      - config
      - mysql

  service-a:
    image: spring-boot-cloud/service-a
    hostname: service-a
    restart: on-failure
    ports:
      - "8001:8001"
    external_links:
      - registry
      - rabbitmq
      - config

  service-b:
    image: spring-boot-cloud/service-b
    hostname: service-b
    restart: on-failure
    ports:
      - "8002:8002"
    external_links:
      - registry
      - rabbitmq
      - config
