version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15673:15672
  registry:
    image: spring-boot-cloud/registry
    hostname: registry
    restart: on-failure
    ports:
      - "8080:8080"
  config:
    image: spring-boot-cloud/config
    hostname: config
    restart: on-failure
    ports:
      - "8888:8888"
    depends_on:
      - registry
      - rabbitmq
