
server:
  port: 8443

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/
spring:
  application:
    name: gateway-web

  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PROT:6379}
    lettuce:
      pool:
        max-active: 300

  security:
    oauth2:
      client:
        jwt:
          signingKey: testKey

  cloud:
    gateway:
      default-filters:
      - name: Retry
        args:
          retries: 3
          statuses: BAD_GATEWAY
      - name: RequestRateLimiter
        args:
          redis-rate-limiter.replenishRate: 2  #流速 每秒
          redis-rate-limiter.burstCapacity: 10   #令牌桶的容积
          rate-limiter: "#{@defaultRedisRateLimiter}"  #SPEL表达式去的对应的bean
          key-resolver: "#{@apiKeyResolver}" #SPEL表达式去的对应的bean

gateway:
  ignore:
    authentication:
      url: /oauth,/open

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.swp.cloud.gateway: debug
    com.jalja.org.spring: debug
  path: logs/
  file:
    max-size: 1GB