
spring:

  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USER:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

  redis:
    host: ${REDIS_SERVER:49.233.168.132}
    port: ${REDIS_PROT:6379}
    lettuce:
      pool:
        max-active: 20

# DATASOURCE
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOUCE_HOST:49.233.168.132}:${DATASOURCE_PORT:3306}/sc_auth?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:Shi18740961619?}

  mvc:
    throw-exception-if-no-handler-found: true

  security:
    oauth2:
      jwt:
        signingKey: 123456

  cloud:
    loadbalancer:
      retry:
        enabled: true
logging:
  level:
    org.springframework.web: debug
    org.springframework.security: debug
    java.sql.PreparedStatement: debug
    org.apache.ibatis: debug
  path: logs/
  file:
    max-size: 1GB

feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true


