spring:

  cloud:
    config:
      discovery:
        service-id: config
        enabled: true
      name: service-b
      profile: pro
    bus:
      trace:
        enabled: true
      enabled: true

  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest



feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always