version: '3'
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: sc-nacos-standalone
    networks:
      - sc-net
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - JVM_OPTS=-Xmx1g -Xms1g -Xmn512m -XX:MaxPermSize=1024m
    volumes:
      - ../data/nacos-server/logs/:/home/nacos/logs
    ports:
      - "8848:8848"