version: '3'
services:
  bus-server:
    image: cike/bus-server:latest
    container_name: sc_bus
    restart: always
    networks:
      - sc-net
    ports:
      - 8071:8071
    env_file: .env
    environment:
      TZ: Asia/Shanghai