version: '3'
services:

  redis:
    image: redis:alpine
    container_name: sc-redis
    restart: always
    volumes:
      - ../data/redis:/data
    environment:
      - REDIS_PASSWORD=123456
    networks:
      - sc-net
    ports:
      - 6379:6379
    env_file: .env

  rabbitmq:
    image: rabbitmq:alpine
    container_name: sc-rabbitmq
    restart: always
    volumes:
      - ../data/rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      - sc-net
    ports:
      - 5672:5672
    env_file: .env

  mysql:
    image: mysql:5.6
    container_name: sc-mysql
    restart: always
    volumes:
      - ../data/mysql:/var/lib/mysql
    networks:
      - sc-net
    ports:
      - 3306:3306
    env_file: .env
    environment:
      # 环境变量
      - MYSQL_ROOT_PASSWORD=Shi18740961619?

networks:
  sc-net:
    external: false