version: '3'
services:

  #组织服务
  organization:
    image: cike/organization:latest
    container_name: sc-organization
    restart: always
    networks:
      - sc-net
    ports:
      - 8010:8010
    env_file: .env
    environment:
      TZ: Asia/Shanghai